### ISSUE TITLE
Grunt crash on syntax error parser

### ISSUE THREAD

**Issue by ssavajols** [gruntjs/grunt-contrib-requirejs#82]
Hi,

Is it possible to not crash grunt on syntax error during the compilation ?

It's not really comfortable to re-launch grunt every time we save a file with syntax error in it. 

A "force" option could be helpful to prevent grunt exit.

``` javascript
Error: Parse error using esprima for file
```

**Comment by Blasz** [comment]
That option for grunt-contrib-watch only handles `grunt.fatal` and `grunt.warn`, unhandled errors aren't going to be caught.

The issue is that any errors that are thrown by requirejs are not being caught. This grunt plugin should be catching these errors and calling grunt.fail instead of not handling them at all.

This plugin is supposed to make requirejs compatible with grunt. Catching errors and interfacing them with grunt's fail API should be a part of that process.
